"""Export a single-file, zero-install HTML console snapshot from a real run's
out/ artifacts (spec §7 Day-3 ②). No server, no key, works offline from a
double-click; the header says exactly what it is.

    .venv/bin/python scripts/export_console.py   # writes reports/console-snapshot.html
"""
import json
import re
import sys
from datetime import datetime
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.closure import closure_state, time_to_close_hours, volume_subsided  # noqa: E402
from src.metrics import _CSS, _fmt_money, risk_exposure, stuck_funds  # noqa: E402

_EXTRA_CSS = """
.qrow td { font-size:12.5px; }
.pin { color: var(--critical); font-weight:700; }
details { margin:8px 0; }
details summary { cursor:pointer; color:var(--ink-2); font-size:13.5px; }
details pre { background:var(--card); border-radius:8px; padding:12px 14px;
  overflow-x:auto; font-size:12px; line-height:1.5; white-space:pre-wrap; }
.hdrnote { background:var(--card); border-left:3px solid var(--bar);
  padding:10px 14px; border-radius:6px; font-size:13px; color:var(--ink-2); }
"""


def _closure_text(c, by_id, actions, events):
    times = [by_id[t]["created_at"] for t in c["member_ids"] if t in by_id]
    if not times:
        return "—"
    end = max(t["created_at"] for t in by_id.values())
    subsided = volume_subsided(times, end)
    state, _ = closure_state(c["cluster_id"], actions, events, subsided=subsided)
    if state is None:
        return "detected"
    ttc = time_to_close_hours(c["cluster_id"], actions, min(times))
    out = state + (f" · time-to-close {ttc:.0f}h" if ttc is not None else "")
    return out + ("" if subsided else " (theme still active — cannot close)")


def build_console(queue, clusters, actions, artifacts, by_id, generated):
    """queue: ops_queue.json list · clusters: clusters.json dict · actions:
    actions.jsonl list · artifacts: {relpath: markdown} · by_id: tickets."""
    events = [{"event": "INCIDENT_DECLARED", "cluster_id": c["cluster_id"],
               "created_at": str(c["first_seen"])}
              for c in clusters.get("incidents", []) + clusters.get("trends", [])]

    enriched_like = {q["ticket_id"]: q for q in queue}
    tiles = "".join(
        f'<div class="tile"><div class="v">{v}</div><div class="l">{l}</div></div>'
        for v, l in [
            (len(queue), "tickets triaged"),
            (sum(1 for q in queue if q["pinned"]), "risk tickets pinned"),
            (f'{len(clusters.get("incidents", []))} + {len(clusters.get("trends", []))}',
             "incidents + trends"),
            (len(actions), "audited actions"),
        ])

    cards = ""
    for c in clusters.get("incidents", []) + clusters.get("trends", []):
        badge = ("inc", "&#9650; INCIDENT") if c["kind"] == "incident" else ("trd", "&#9888; TREND")
        cards += (f'<div class="card"><span class="badge {badge[0]}">{badge[1]}</span> '
                  f'<strong>{c["cluster_id"]}</strong> · {escape(c["theme"])}'
                  f'<div class="meta">{len(c["member_ids"])} tickets · '
                  f'{len(c["customers"])} customers · avg CSAT {c["avg_csat"]} · '
                  f'closure: <strong>{_closure_text(c, by_id, actions, events)}</strong></div></div>')

    qrows = "".join(
        f'<tr class="qrow"><td>{"<span class=pin>📌</span> " if q["pinned"] else ""}'
        f'{q["ticket_id"]}</td><td>{escape(q["customer_name"])}</td>'
        f'<td>{q["segment"]}</td><td>{escape(q["theme"])}</td>'
        f'<td class="num">{q["priority"]}</td><td>{escape(q["explain"])}</td></tr>'
        for q in queue)

    docs = "".join(
        f'<details><summary>{escape(name)}</summary><pre>{escape(text)}</pre></details>'
        for name, text in artifacts.items())

    trail = "".join(
        f'<tr><td>{a["ts"][:16]}</td><td>{escape(a["actor"])}</td>'
        f'<td>{escape(a["action"])}</td><td>{escape(a.get("artifact") or "")}</td></tr>'
        for a in actions[-30:])

    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ops Console Snapshot</title><style>{_CSS}{_EXTRA_CSS}</style></head><body><main>
<h1>Ops Control Tower — console snapshot</h1>
<div class="hdrnote">This is a <strong>snapshot of a real run</strong>, generated by
<code>export_console.py</code> from the pipeline's own output files on {generated}.
Zero install, zero network, no API key — what you see is what the tool produced.</div>

<h2>Run at a glance</h2>
<div class="tiles">{tiles}</div>
{cards}

<h2>The queue (all tickets, risk pinned first — every score explained)</h2>
<div class="card" style="overflow-x:auto"><table>
<tr><th>ticket</th><th>customer</th><th>segment</th><th>theme</th>
<th class="num">priority</th><th>why this rank</th></tr>{qrows}</table></div>

<h2>Agent-produced artifacts (verbatim)</h2>
{docs}

<h2>Audit trail (latest 30 actions)</h2>
<div class="card"><table>
<tr><th>when</th><th>actor</th><th>action</th><th>artifact</th></tr>{trail}</table></div>

<footer>Generated by export_console.py · single file · safe to forward</footer>
</main></body></html>"""


def main():
    out_dir = ROOT / "out"
    queue = json.loads((out_dir / "ops_queue.json").read_text())
    clusters = json.loads((out_dir / "clusters.json").read_text())
    actions = [json.loads(l) for l in (out_dir / "actions.jsonl").read_text().splitlines()
               if l.strip()] if (out_dir / "actions.jsonl").exists() else []

    from src.adapters.csv_adapter import CsvAdapter
    by_id = {t["ticket_id"]: t for t in CsvAdapter(ROOT / "data/tickets.csv").fetch_tickets()}

    artifacts = {}
    for pat in ["incidents/*.md", "trends/*.md", "workpackages/*.md",
                "knowledge/outbound/eng/*.md", "knowledge/outbound/product/*.md"]:
        for f in sorted(ROOT.glob(pat)):
            rel = str(f.relative_to(ROOT))
            artifacts[rel] = f.read_text()

    html = build_console(queue, clusters, actions, artifacts, by_id,
                         generated=datetime.now().strftime("%Y-%m-%d %H:%M"))
    # secret/path scan before write (spec §Security)
    for bad in [re.compile(r"sk-[A-Za-z0-9_-]{10,}"), re.compile(r"/Users/[A-Za-z0-9_.-]+")]:
        hits = bad.findall(html)
        if hits:
            sys.exit(f"REFUSING to write console: leaked pattern {hits[:2]}")
    dest = ROOT / "reports" / "console-snapshot.html"
    dest.write_text(html)
    print(f"wrote {dest} ({len(html) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
